[features]
seeds = false
skip-lint = false
[programs.localnet]
postfeedapp = "8gXmb5owBUq1Fir1XsEc7zachbU7K396F6GuW2sxLHJx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/billyzhang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
